Use fail() instead of assertEqual() with length check
When the flake8 or pylint call detects issues, the test will fail:

AssertionError: 163 != 0 : flake8 found issues:
[...]

AssertionError: 1177 != 0 : pylint3 found issues:
[...]

The length comparison '163 != 0' might be confusing. Thus do the length
check manually and use fail() in case of a failure. The output will be
cleaner:

AssertionError: flake8 found issues:
[...]

AssertionError: pylint3 found issues:
[...]